/** @format */

import { League_Spartan } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weights: [500, 700],
});

export const metadata = {
  title: "Job Listings with Filtering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          leagueSpartan.className,
          "antialiased",
          "text-tertiary",
          "font-bold",
          "bg-lighter",
          "pt-[7.5rem]",
          "bg-[url('/images/bg-header-mobile.svg')]",
          "bg-repeat-x",
        )}
      >
        <div className="desktop:max-w-[69.375rem] mx-auto flex max-w-[23.4375rem] flex-col px-[1.5rem]">
          {children}
        </div>
      </body>
    </html>
  );
}
