/** @format */

import { League_Spartan } from "next/font/google";
import { twMerge } from "tailwind-merge";
import "./globals.css";

const leagueSpartan = League_Spartan({
  subsets: ["latin"],
  weights: [500, 700],
});

export const metadata = {
  title: "Job Listings with Filtering",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={twMerge(
          leagueSpartan.className,
          "antialiased",
          "text-tertiary",
          "font-bold",
          "bg-lighter",
          "pt-[7.5rem]",
        )}
      >
        {children}
      </body>
    </html>
  );
}
